### all subscribers

GET http://localhost:3030/subscribers/

### get specific subscriber

GET http://localhost:3030/subscribers/64944247a6281368ffe54717

### create new subscriber

POST http://localhost:3030/subscribers/
Content-type: application/json

{
    "name": "John",
    "subscribedToChannel": "Somechannel"
}


### delete subscriber

DELETE http://localhost:3030/subscribers/64944247a6281368ffe54717


### update info

PATCH http://localhost:3030/subscribers/64944247a6281368ffe54717
Content-type: application/json

{
    "name": "Dave"
}
